### ISSUE TITLE
1/2-1/3 = 5/6

### ISSUE THREAD

**Issue by alexs10** [kylelin47/COP-Project#34]
More negetive issues. Kyle are you coming to the lab today?

**Comment by kylelin47** [comment]
yeah sure.

**Comment by kylelin47** [comment]
at its core, the issue is that multexpression has a sign in the first place. same as with integer, the sign is implicit within its value. by assigning multexpression a sign, you have to state whether (-2/3) with sign - is 2/3 or -2/3.

it's not like you ever multiply multexpressions by multexpressions and have to know the resulting sign - you multiply each element and each element decides what its new sign is.

sign should never have been implemented on multexpression, just as it doesn't exist on sum expression

**Comment by alexs10** [comment]
Before you multiply the two mult expressions, create a new sign varaiable = to the correct output sign. Then at the end when you create a multExpression, feed it that sign.
